name: talk_nest
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  provider: ^6.1.2
  firebase_database: ^11.2.0
  google_fonts: ^6.2.1
  random_string: ^2.3.1
  fluttertoast: ^8.2.8
  lottie: ^3.2.0
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  flutter_social_button: ^1.1.6+1
  flutter_vector_icons: ^2.0.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.7
  google_nav_bar: ^5.0.7
  hugeicons: ^0.0.7
  flutter_contacts: ^1.1.9+2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  date_format: ^2.0.9
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  image_cropper: ^8.1.0
  firebase_messaging: ^15.1.4
  http: ^1.2.2
  flutter_local_notifications: ^18.0.0
  googleapis_auth: ^1.6.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.1.2
  zego_uikit_prebuilt_call: ^4.16.21
  floaty_nav_bar: ^1.0.1
  share_plus: ^10.1.4
  firebase_dynamic_links: ^6.1.2
  firebase_analytics: ^11.4.2
connectivity_plus: ^3.0.5






dev_dependencies:
  flutter_test:
    sdk: flutter



  
  flutter_lints: ^4.0.0





flutter:


  uses-material-design: true

  
  
  
  
  assets:
    - assets/images/
    - assets/lottie/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
