// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr17SomRcOf3BJCrghpaN5qDF9td6TOQs',
    appId: '1:1096585580375:web:86c0d677e17aa87b72b812',
    messagingSenderId: '1096585580375',
    projectId: 'flutterfirebaseauth-439e4',
    authDomain: 'flutterfirebaseauth-439e4.firebaseapp.com',
    databaseURL:
        'https://flutterfirebaseauth-439e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebaseauth-439e4.appspot.com',
    measurementId: 'G-265VQY57QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFXRYw4FNZ8405wOlMJPcXYLh5ooAx70Y',
    appId: '1:1096585580375:android:6dd894cc2a54aede72b812',
    messagingSenderId: '1096585580375',
    projectId: 'flutterfirebaseauth-439e4',
    databaseURL:
        'https://flutterfirebaseauth-439e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebaseauth-439e4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEA6DbPimk65qRjLU4ymjTDmt7lgwq8Cg',
    appId: '1:1096585580375:web:8bad218b431a178072b812',
    messagingSenderId: '1096585580375',
    projectId: 'flutterfirebaseauth-439e4',
    authDomain: 'flutterfirebaseauth-439e4.firebaseapp.com',
    databaseURL:
        'https://flutterfirebaseauth-439e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebaseauth-439e4.appspot.com',
    measurementId: 'G-1T6E65TE9H',
  );
}
